version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chevrolet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/chevrolet
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
