version: '3.7'

services:
  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: ./app
    command: celery -A celery_worker.app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

